### ISSUE TITLE
Add drag and drop functionality

### ISSUE THREAD

**Issue by GrilledCheeese** [codevirtuel/osu-replayViewer-web#1]
Dragging an osu replay file into the browser having your website recognise the osu replay file and location will save me from having to browse to the file itself or make a copy to a more easily approachable folder just to be able to upload it.

**Comment by codevirtuel** [comment]
I've added the drag and drop functionality. You can drag your file into the border dotted block.
I'm looking into adding some user feedback, like color when you drag the file into the box.
