### ISSUE TITLE
Error uploading skin

### ISSUE THREAD

**Issue by ballup77** [codevirtuel/osu-replayViewer-web#15]
**Describe the bug**
I tried to upload a skin onto osu and I get an error saying that I cannot upload skin due to the skin already being uploaded.

**To Reproduce**
1. Go to osu skin folder to see if skin.ini is already in lowercase
2. If it is in lowercase go onto osu and export as osz
3. Upload to replay website
4. Get error

**Expected behavior**
if i take the skin and try to upload it will not let me.

**Screenshots**
![error](https://user-images.githubusercontent.com/43057362/45199645-b67b5100-b221-11e8-8699-dcb28e74a322.PNG)
![skin ini fail](https://user-images.githubusercontent.com/43057362/45199646-b67b5100-b221-11e8-8964-87c333616f33.PNG)

**Comment by codevirtuel** [comment]
Fixed in last update v0.2.0
