### ISSUE TITLE
Unable to create an account.

### ISSUE THREAD

**Issue by zeatgithub** [codevirtuel/osu-replayViewer-web#16]
**description**
I've tried numerous times to create a new account, but every time I fill my information out, accept the terms and tick the captcha, it prompts me to fill out my osu! ID and my email address even though both are perfectly valid. I'm not sure of whether or not it's the website's fault, or if i'm just missing something. 

**replication**
Here is a video of me replicating the bug:
https://streamable.com/8jnnl

**expected behavior**
given that my osu! ID is valid and linked to my account, and that my email address is active and working I saw no reason initially as to why account creation wouldn't have worked. I expected the account creation to go smoothly.

**desktop**
Windows 7 64bit Home Premium
Waterfox, latest version.
(i've also tried with the latest version of firefox, with no luck)

**additional info**
the boxes for 'accept terms' 'osu! id' and 'email address' were all red even after visiting the register page for the first time without ever entering any information, which leads me to believe its a problem on the site's end and not mine.

if this could be fixed, it would be greatly appreciated

**Comment by codevirtuel** [comment]
Should be fixed, thx for the report and sorry :/
