### ISSUE TITLE
Disqus Chat and Page view count

### ISSUE THREAD

**Issue by SilverEyesJP** [codevirtuel/osu-replayViewer-web#17]
**It would be nice if we had a Discus chat on every replay page like Osu! has with beatmaps page** https://disqus.com/

> Other alternative suggestion is if we could send an private message to other users

**An page view count would works like profile/replay views count**

**Comment by codevirtuel** [comment]
Added in last release https://github.com/codevirtuel/osu-replayViewer-web/releases/tag/v0.2.2
