### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by RegularLuck** [codevirtuel/osu-replayViewer-web#21]
I try to register and I get redirected to a page that says this:

Warning: require_once(/var/www/ws86us/www/secure/smtp.php): failed to open stream: No such file or directory in /var/www/ws86us/www/php/verificationFunctions.php on line 13

Fatal error: require_once(): Failed opening required '/var/www/ws86us/www/secure/smtp.php' (include_path='.:/opt/phpfarm/inst/php-5.6.5/pear/php/') in /var/www/ws86us/www/php/verificationFunctions.php on line 13

Pls fix

**Comment by codevirtuel** [comment]
Indeed, a file was missing on the server. This should be fixed now.
Have a nice day
