### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by Piotrekol** [codevirtuel/osu-replayViewer-web#3]
By searching for UserId 
`1 or 1=1`  
![chrome_2018-02-05_15-26-58](https://user-images.githubusercontent.com/4990365/35809505-2a49fd34-0a89-11e8-98b6-7ca0a94e1062.png)
I'm able to see all uploaded/queued replays.
Easiest way to protect against this particular issue is to cast used variable to int/ ideal would be to use prepared statements.

Read about SQL injection and how to avoid it.

**Comment by codevirtuel** [comment]
Thank you i'm looking into that

**Comment by codevirtuel** [comment]
Fixed, thanks for your issue.
