### ISSUE TITLE
Mania replay not uploading (probably not supported) and now stuck on "Currently in processing queue" forever.

### ISSUE THREAD

**Issue by AikawaSora** [codevirtuel/osu-replayViewer-web#4]
![image](https://user-images.githubusercontent.com/36181928/35842019-9d83150e-0b3a-11e8-8179-29e8564f07fa.png)

I tried uploading a mania replay after a standard replay and now it's been uploading and says "Currently in processing queue" forever. I tried dragging another standard replay to upload just to see if it'd upload even if the mania one didn't finish yet but no luck. it's been I think 2hrs since I did this.

**Comment by codevirtuel** [comment]
I think it's because your replay file was corrupted.
Send me a screenshot of your replay playing and I'll look for the bug.
