### ISSUE TITLE
Can't find my replay

### ISSUE THREAD

**Issue by Kitsuneko-Ztz** [codevirtuel/osu-replayViewer-web#5]
I've been uploaded 2 replays and when i tried to search it 
![image](https://user-images.githubusercontent.com/31190505/35847667-c615544c-0b4d-11e8-8a34-4e61a3132ab6.png)
with underscore
![image](https://user-images.githubusercontent.com/31190505/35847703-e9ae8298-0b4d-11e8-8783-3619e5ba829e.png)
without underscore (using space)
![image](https://user-images.githubusercontent.com/31190505/35847738-11d1d040-0b4e-11e8-8597-4f1c0796fad6.png)
even with the user_ID

**Comment by codevirtuel** [comment]
I've fix this issue.
Thank you and have fun !
