### ISSUE TITLE
code quality + security vulnerabilities

### ISSUE THREAD

**Issue by IOExceptionOsu** [codevirtuel/osu-replayViewer-web#9]
hi it seems you're pretty new to php. here's some tips:

- use [mysql prepared statements](https://www.w3schools.com/php/php_mysql_prepared_statements.asp) to avoid sql injections. i know someone else brought it up already but mysql injections are one of the things attacked most frequently. know how it works so your server doesn't get attacked. 
- [actually, this stuff should go into the secure/ folder too](https://github.com/codevirtuel/osu-replayViewer-web/blob/master/index.php#L9)
- don't display PHP errors on user-facing pages (for example, going to [this page](https://osureplayviewer.xyz/view.php) without an ID). errors in PHP are really tricky, since most people just seem to silence / ignore them. get rid of your errors in development, so they don't show up during production!
- [dont' commit your oauth secret](https://github.com/codevirtuel/osu-replayViewer-web/blob/2fa89b78051f666a148b68fd50a256d616eac11b/test2.php#L34)

i haven't looked much more into it but there's a lot of red flags in there. good luck

**Comment by codevirtuel** [comment]
Thank you, 

I'm updating all of this as soon as possible :)
(i've already learn a lot on mysql prepared statements).

And please, if you see another issue. Contact me again.
